# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# build Configuration, i.e. Debug, Release, etc.
configuration: Release



# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                    # enable MSBuild parallel builds
  project: CodilityTest.sln      # path to Visual Studio solution or project




#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - CodilityTest.dll


