# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# build Configuration, i.e. Debug, Release, etc.
configuration: Release


environment:
  COVERALLS_REPO_TOKEN:
    secure: 1oUKnd1XbQ0oGHRiWmY2IG2enOrsSP0qGxtcI7M3uYW9W5S7ZClV6IRLnxDOg9vB

before_build:
  - nuget restore CodilityTest.sln


build:
  parallel: true                    # enable MSBuild parallel builds
  project: CodilityTest.sln      # path to Visual Studio solution or project




#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- ps: .\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:.\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe "-targetargs:"".\CodilityTest\bin\$env:CONFIGURATION\CodilityTest.dll"" /noshadow" -filter:"+[CodilityTest*]*" -output:opencoverCoverage.xml

- ps: $env:COVERALLS_REPO_TOKEN
- ps: $env:APPVEYOR_REPO_COMMIT
- ps: $env:APPVEYOR_REPO_BRANCH
- ps: $env:APPVEYOR_REPO_COMMIT_AUTHOR
- ps: $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
- ps: $env:APPVEYOR_REPO_COMMIT_MESSAGE
- ps: $env:APPVEYOR_BUILD_NUMBER

- ps: .\packages\coveralls.net.0.6.0\tools\csmacnz.coveralls.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_BUILD_NUMBER --serviceName appveyor